Repository Romeslayer/fitlit, pull requests merged in 2022-02, with the labels that each got.

#14 Close #13 - Feature/build user repository class
  package-lock.json
  src/data/user-test-data.js
  test/UserRepository-test.js
Labels: Iteration 1

#15 Close #12 - Write User test
  test/User-test.js
Labels: Iteration 1

#16 Close #2 - Build User Class and change UserRepository file path
  src/UserRepository.js
  src/js/User.js
  src/js/UserRepository.js
  test/User-test.js
Labels: Iteration 1

#17 Close #1 - Build UserRepository Class and add file path to UserRepository-test.js
  src/js/UserRepository.js
  test/UserRepository-test.js
Labels: Iteration 1

#20 Close #11 - Remove users data file
  src/data/users.js
Labels: Iteration 2

#22 Close #5 - Display Hydration data to dashboard
  src/scripts.js
Labels: Iteration 3

#24 Close #7 - Add sleep hours and sleep quality data to DOM display
  dist/index.html
  src/scripts.js
Labels: Iteration 4
